# Site settings
baseurl = "https://templeman.io/"
themesDir = "themes"
languageCode = "en-us"
title = "Templeman Creative"
theme = "cactus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
# Disable comments by leaving disqusShortname empty
disqusShortname = "spf13"

[params]
  name = "Sam Templeman"
  description = "Sam Templeman is a full-stack web designer in Portland, Oregon"
  bio = "Full-stack web designer in Portland, Oregon."
  # Enter optionally your twitter account
  twitter = "@samueltempleman"
  enableRSS = true

  # Integrate Javascript files or stylesheets by adding the url to the external
  # assets or by linking local files with their path relative to the static
  # folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home = ""
  subscribe = ""
  # Pagination links
  olderPosts = ""
  newerPosts = ""
  readMore = ""
  copyright = "MMXX"
  # Sharing options and author information in posts
  aboutAuthor = "I'm a blogger."
  tweet = ""
  share = ""
  # 404 page
  title404 = ""
  subtitle404 = ""

  # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
  iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

  # sectionPagesMenu = "main"

[[menu.main]]
    name = "About"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

[[menu.main]]
    name = "Notes"
    url = "/note/"
    weight = 3


# Add additional social link entries underneath
[social]
    github   = "https://github.com/templeman"
    twitter  = "https://twitter.com/samueltempleman"
    linkedin = "https://www.linkedin.com/in/samtempleman/"
